### ISSUE TITLE
MacOS: gitk freezes when resizing window

### ISSUE THREAD

**Issue by wilhelmy-fielmann** [dracula/gitk#10]
After copying the config file, gitk opens and shows the theme correctly. However, resizing the window freezes the application. Resizing the panels do not cause it to freeze.

I've narrowed the offending config line to:
`set want_ttk 0`
By removing it, gitk automatically fills it up (after a launch) with:
`set want_ttk 1`

This makes resizing work without freezing.

Environment:
Git v2.36.0
MacOS 12.3.1
CPU: M1 Max

**Comment by lourot** [comment]
Thanks @RawBOT! Out of curiosity, then I suppose with `set want_ttk 1` some parts of the UI aren't following the theme, as described in https://github.com/dracula/gitk/issues/4#issuecomment-553790057 ?

**Comment by lourot** [comment]
The issues preventing us from using `set want_ttk 0` have been fixed in
* https://github.com/git/git/pull/1219
* https://github.com/git/git/commit/ef9b086d

The first version containing this fix is `v2.37.0`. On Ubuntu for example it's
available starting from Ubuntu 22.10 (Kinetic):
https://packages.ubuntu.com/kinetic/gitk

I have just tried it out and everything works well now for me.
